### ISSUE TITLE
math

### ISSUE THREAD

**Issue by slowy07** [bellshade/Python#105]
## description
series implementasi beberapa matematika dengan python, dan hasil dari semua ini terdapat pada folder [math](https://github.com/bellshade/Python/tree/main/math)
mencakup:
- [x] [keselarasan zeller](https://github.com/bellshade/Python/blob/math/math/zellers_congruence.py)
- [x] [hitung volume](https://github.com/bellshade/Python/blob/math/math/volume.py)
- [x] [nomor aneh ( ugly numbers )](https://github.com/bellshade/Python/blob/math/math/ugly_number.py)
- [x] [two sum](https://github.com/bellshade/Python/blob/math/math/two_sum.py)
- [x] [two pointer](https://github.com/bellshade/Python/blob/math/math/two_pointer.py)
- [x] #116
- [x] #117
- [x] #118
- [x] #119
- [x] #120
- [x] [fungsi relu](https://github.com/bellshade/Python/blob/main/math/relu.py)
- [x] #126
- [x] #127
- [x] #125
- [x] #133
- [x] #136
- [x] #134
- [x] #154
- [x] #155
- [x] #156
- [x] #188
- [x] #137
- [x] #135

next update

## saya menggunakan
OS : ``Linux / Windows / MacOS``
Python: ``diatas versi 2 dibawah versi 3.10``

## tambahan lainnya
- buka issue yang ingin dipilih kemudian assign
- lakukan fork
- kemudian lakukan perubahan atau penambahan sesuai dari issue
- menggunakan type hints dan doctstring sebagai contoh dibawah ini
```python
def hitung_diameter_lingkaran(radius: float) -> float:
 """
 menghitung diameter dari sebuah lingkaran
 rumus:
 diameter: 2 * radius
 >>> hitung_diameter_lingkaran(12)
 24.0
 """
 return float(2 * radius)
```
kemudian disarankan dengant testing lokal dengan menginstall flake8 dan pytest
**pytest**
```bash
pytest . --doctest-modules --ignore=Basic/
```
atau bisa juga dengan
```bash
pytest namafile.py --doctest-modules --ignore=Basic/
```
flake8
```bash
flake8 . --ignore=E203,W503,W504 --max-complexity=25 --max-line-length=88
```

- jika sudah maka lakukan pull request
- usahakan message commitnya mengikuti dari salah satu dibawah ini (contoh)
  - ``add: menambahkan algoritma sigmoid``
  - ``feat: menambahkan algoritma sigmoid``
  - ``fix: memperbaiki kesalahan pada algoritma sigmoid``
 - membaca [peraturan dan pedoman kontribusi](https://github.com/bellshade/Python/blob/main/CONTRIBUTING.md)

**Comment by sykrabadi** [comment]
assign nya ini self assign atau tunggu di assign mas?

**Comment by slowy07** [comment]
assign deret geomtri @sykrabadi
