### ISSUE TITLE
Menambahkan materi standar pustaka (standard library) pada Python

### ISSUE THREAD

**Issue by fadhilc97** [bellshade/Python#107]
## description
Saya ingin menambahkan materi tentang standar pustaka (_standard library_) pada _Python_ yang sering digunakan

## saya menggunakan
OS : ``Linux``
Python: ``version 3.9.6``

**Comment by fadhilc97** [comment]
Saya mau menjelaskan penggunaan library `datetime` dan `math`

**Comment by slowy07** [comment]
LGTM, nanti usahakan pull request ke branch ``main`` dengan perubahan dilakukan di dalam folder ``basic`` dan membuat folder berupa ``python_datetime`` dan folder ``math`` 
untuk contoh bisa struktur folder bisa dilihat [disini](https://github.com/bellshade/Python/tree/main/Basic)
