### ISSUE TITLE
List & Dictionary Comprehensive

### ISSUE THREAD

**Issue by adeyusuf211** [bellshade/Python#110]
## saya menggunakan
OS : ``Windows``
Python: ``version 3``

## tambahan lainnya
Saya ingin membuat materi tentang list dan dictionary comprehensive.

**Comment by slowy07** [comment]
issue di close karena tidak ada perubahan atau pull request yang berhubungan dengan issue ini

**Comment by KelvinMulyawan** [comment]
sensei @slowy07 berarti koding nya belum ada kah ? kalau emang belum ada, boleh assign ga sensei ?

**Comment by slowy07** [comment]
belum, buat aj issue baru kemudian assignkan @KelvinMulyawan
