### ISSUE TITLE
Penambahan script dan penjelasan tentang doubly linked list (DLL)

### ISSUE THREAD

**Issue by sykrabadi** [bellshade/Python#147]
## description

Menambahkan script tentang doubly linked list, beserta penjelasan tentang pembahasan tersebut dalam bentuk markdown

## saya menggunakan
OS : ``Windows 10``
Python: ``3.9.5``

**Comment by sykrabadi** [comment]
Halo mas @slowy07 , bisa assign issue ini ke saya?

**Comment by slowy07** [comment]
boleh2 assing @sykrabadi
