### ISSUE TITLE
abstraksi

### ISSUE THREAD

**Issue by slowy07** [bellshade/Python#171]
penerapan konsep abstaksi oop
struktur folder bisa dilihat pada #170

**Comment by AdhyWiranto44** [comment]
kak @slowy07, saya mau ambil issue ini

**Comment by slowy07** [comment]
boleh2, tadi saya rencana mau assign juga, lanjutkan :100: @AdhyWiranto44

**Comment by AdhyWiranto44** [comment]
siapp
