### ISSUE TITLE
inheritance ( pewarisan )

### ISSUE THREAD

**Issue by slowy07** [bellshade/Python#172]
Inheritance (Pewarisan) merupakan salah satu dari tiga konsep dasar OOP. Konsep inheritance ini mengadopsi dunia riil dimana suatu entitas/obyek dapat mempunyai entitas/obyek turunan. Dengan konsep inheritance, sebuah class dapat mempunyai class turunan.

untuk struktur folder bisa dilihat pada issue #170

**Comment by AdhyWiranto44** [comment]
Saya mau ambil inheritance ya kak

**Comment by slowy07** [comment]
oke lanjutkan @AdhyWiranto44 :100:

**Comment by slowy07** [comment]
close karena issue solved
