### ISSUE TITLE
Penambahan algoritma -> Pascal Triangle on Math Folder

### ISSUE THREAD

**Issue by KelvinMulyawan** [bellshade/Python#180]
## saya menggunakan
OS : ``Windows``
Python: ``3.9``

## tambahan lainnya

Boleh sensei @slowy07 ?

**Comment by slowy07** [comment]
boleh go on, pake docstring nnti @KelvinMulyawan

**Comment by KelvinMulyawan** [comment]
sip sensei @slowy07

**Comment by slowy07** [comment]
issue sudah solve
