### ISSUE TITLE
Penambahan Tutorial Rest API using flask

### ISSUE THREAD

**Issue by IlhamriSKY** [bellshade/Python#187]
Hallo Team Bellshade, saya tertarik dengan konsep repositori tutorial menggunakan bahasa indonesia.

Saya ingin berkontribusi mengenai rest api menggunakan python, namun sepertinya tidak masuk kedalam tipe tutorial yang tertera pada readme.

Contoh tutorial saya dapat dilihat disini [Rest Api](https://github.com/IlhamriSKY/Rest-Api-Tutorial).

**Comment by slowy07** [comment]
masukkan ke dalam folder ``web_programming`` kemudian lakukan langkah dibawah ini ( jika pull request sesuai, silahkan ceklist )
- [ ] membuat file yang bernama ``flask_api``
- [ ] di dalam folder berikan contoh penggunaaan dari flask api 
- [ ] memberikan komentar yang informatif pada baris kode

sebelumnya jangan lupa juga baca [peraturan dari kontribusi](CONTRIBUTING.md) yang terdapat pada file yang bernama ``CONTRIBUTING.md``

**Comment by IlhamriSKY** [comment]
> masukkan ke dalam folder `web_programming` kemudian lakukan langkah dibawah ini ( jika pull request sesuai, silahkan ceklist )
> 
> * [ ]  membuat file yang bernama `flask_api`
> * [ ]  di dalam folder berikan contoh penggunaaan dari flask api
> * [ ]  memberikan komentar yang informatif pada baris kode
> 
> sebelumnya jangan lupa juga baca [peraturan dari kontribusi](https://github.com/bellshade/Python/blob/main/CONTRIBUTING.md) yang terdapat pada file yang bernama `CONTRIBUTING.md`
* [x] membuat file yang bernama `flask_api`
* [x] di dalam folder berikan contoh penggunaaan dari flask api
* [x] memberikan komentar yang informatif pada baris kode

**Comment by slowy07** [comment]
closed issue
