### ISSUE TITLE
BUG error file CODEOWNERS

### ISSUE THREAD

**Issue by ranggakd** [bellshade/Python#206]
## Masalah

Terdapat pesan error pada file CODEOWNERS.

## Screenshots atau contoh error

![image](https://user-images.githubusercontent.com/36787606/193455881-65971d71-4aac-4cd5-894c-a2b91eda3e62.png)

![image](https://user-images.githubusercontent.com/36787606/193455888-d96b67e9-a542-4c54-ab93-a43f6cb6d920.png)

terima kasih !

**Comment by ranggakd** [comment]
Tidak ditemukannya user @KevinMulyawan dan @hendri-27 pada [contributions graphs](https://github.com/bellshade/Python/graphs/contributors) yang memiliki akses write.  
CMIIW 🙏

**Comment by slowy07** [comment]
issue ditutup karena PR sudah di squash
