### ISSUE TITLE
Penambahan algoritma gradient descent machine learning

### ISSUE THREAD

**Issue by slowy07** [bellshade/Python#227]
## Description

Implementasi algoritma gradient descent untuk meminimalkan cost hipotesis linier
fungsi.

## Saya Menggunakan

OS : ``Linux``  
Python: ``3.10.9``

## tambahan lainnya

parameter variabel:
```
train_data = (
    ((5, 2, 3), 15),
    ((6, 5, 9), 25),
    ((11, 12, 13), 41),
    ((1, 1, 1), 8),
    ((11, 12, 13), 41),
)
test_data = (((515, 22, 13), 555), ((61, 35, 49), 150))
parameter_vector = [2, 4, 1, 5]
m = len(train_data)
LEARNING_RATE = 0.009
```

**Comment by FwydChickn** [comment]
ok sensei @slowy07

**Comment by slowy07** [comment]
close karena pull request sudah di merged
