### ISSUE TITLE
Penambahan list comprehension 

### ISSUE THREAD

**Issue by regiapriandi012** [bellshade/Python#239]
## Description
Hallo, Saya tertarik untuk berkontribusi pada penambahan kode untuk List Comprehension menggunakan contoh nested list atau perulangan bercabang. 

## Saya Menggunakan
OS : ``Windows``  
Python: ``3.8.10``

## tambahan lainnya
Kode yang rapih dan berkualitas pada repo ini memudahkan pemula untuk belajar bahasa pemrograman Python, berharap kedepan lebih banyak yang dapat berkontribusi untuk repo informatif ini.

**Comment by slowy07** [comment]
LGTM,sudah di merge, issue akan di close
