### ISSUE TITLE
Operator

### ISSUE THREAD

**Issue by norinorin** [bellshade/Python#32]
- [x] Operator aritmatika
- [x] Operator penugasan
- [x] Operator perbandingan
- [x] Operator logika
- [x] Operator Identitas
- [x] Operator keanggotaan
- [x] Operator bitwise

**Comment by athallahmaajid** [comment]
I'll take this

**Comment by norinorin** [comment]
Not done yet, re-opening.

**Comment by nomadkode** [comment]
kenapa auto close dia yah wkwkwk

**Comment by norinorin** [comment]
Harusnya sih mention issue aja wkwk, kalo di-link auto-close dia.

**Comment by nomadkode** [comment]
haa I see, terima kasih infonya @norinorin. TIL
