### ISSUE TITLE
Integration Algorithm

### ISSUE THREAD

**Issue by arifyunando** [bellshade/Python#7]
# Integration Algorithm

## Summary
Akan dilakukan implementasi teknik pengintegralan menggunakan metode numerik. Teknik pengintegralan yang akan dilakukan mencakup:
- Aturan persegi panjang
- Aturan titik tengah [*source*](https://chemicalstatistician.wordpress.com/2014/01/20/rectangular-integration-a-k-a-the-midpoint-rule/#:~:text=Rectangular%20integration%20is%20a%20numerical,Here%20are%20its%20features%3A&text=rectangles%20would%20used%20to%20approximate,width%20of%20the%20smaller%20interval.)
- Aturan trapezoid [*source*](https://en.wikipedia.org/wiki/Trapezoidal_rule)
- Aturan Simpson 1/3 [*source*](https://en.wikipedia.org/wiki/Simpson%27s_rule)
- Aturan Simpson 3/8 [*source*](https://en.wikipedia.org/wiki/Simpson%27s_rule)
- Integral multi-dimensi
- Monte Carlo [*source*](https://en.wikipedia.org/wiki/Monte_Carlo_integration#:~:text=In%20mathematics%2C%20Monte%20Carlo%20integration,numerical%20integration%20using%20random%20numbers.&text=While%20other%20algorithms%20usually%20evaluate,useful%20for%20higher%2Ddimensional%20integrals.) 
- Gaussian Quadrature [*source*](https://en.wikipedia.org/wiki/Gaussian_quadrature)

## Catatan
* Seluruh fungsi akan disimpan dalam satu folder `*numerical_integration*`
* Test case akan ditentukan seiring berjalannya waktu

**Comment by slowy07** [comment]
close, pull request merged
