### ISSUE TITLE
Module

### ISSUE THREAD

**Issue by fadhilc97** [bellshade/Python#73]
## description
Materi penggunaan `import` dan `from - import` ketika menggunakan modul bawaan python maupun modul buatan sendiri.

## saya menggunakan
OS : ``Linux``
Python: ``version 3.9.6``

**Comment by fadhilc97** [comment]
> bisa dijelaskn lebih detail ??

Saya mau menambahkan materi penggunaan `import` dan `from ... import ...` baik dari module built-in maupun buatan sendiri

**Comment by slowy07** [comment]
close, PR sudah dikerjakan pada nomor #93
