### ISSUE TITLE
Access modifiers

### ISSUE THREAD

**Issue by sykrabadi** [bellshade/Python#97]
## description

Menambahkan penjelasan tentang access modifiers (public, private, dan protected), serta cara mengakses access modifiers pada folder Basic/class
- [x] #98
- [ ] #99
- [ ] #100

## saya menggunakan
OS : ``Windows 10``
Python: ``3.9.5``

**Comment by sykrabadi** [comment]
ini bisa langsung saya kerjakan mas, tanpa di assign terlebih dahulu?

**Comment by slowy07** [comment]
assign aj terus kak @sykrabadi , nnti saya assign usahakan untuk pull request di link sama issueny kak
